test: "aaa"
db:
  default:
    type: "postgres"
    name: "proofit"
    password: "123456"
    user: "proofit"
    host: "postgres"
auth:
  jwt_secret_token: "jdnfksdmfksd"
  max_username_length: 40
  min_username_length: 8
  min_password_length: 8
admin:
  listen_port: 8080
api:
  listen_port: 8081
swagger:
  path_to_spec: configs/api-spec.yml
  listen_port: 8082
  api_editor_listen_port: 8083
debug: true