db:
  default:
    type: "sqlite"
    name: "test.db"
api:
  listen_port: 5000
auth:
  max_username_length: 40
  min_username_length: 8
  min_password_length: 8
  twofactor_auth_required_for_signin_adapters:
    - direct
swagger:
  path_to_spec: configs/api-spec.yaml
  listen_port: 8082
  api_editor_listen_port: 8083
uadmin:
  secure_cookie: false
  http_only_cookie: false