//go:generate go run github.com/sergeyglazyrindev/uadmin/extras/gendecoder
// Code generated by protoc-gen-gogo. DO NOT MODIFY
// source: blueprint/user/models/generatemodels.proto

package models

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	"github.com/uadmin/uadmin/model"

	io "io"
	math "math"
	math_bits "math/bits"
	"time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	model.Model

	Username             string     `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	FirstName            string     `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string     `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Password             string     `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Email                string     `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Active               bool       `protobuf:"varint,6,opt,name=Active,proto3" json:"Active,omitempty"`
	Admin                bool       `protobuf:"varint,7,opt,name=Admin,proto3" json:"Admin,omitempty"`
	RemoteAccess         bool       `protobuf:"varint,8,opt,name=RemoteAccess,proto3" json:"RemoteAccess,omitempty"`
	UserGroup            UserGroup  `protobuf:"bytes,9,opt,name=UserGroup,proto3" json:"UserGroup,omitempty"`
	UserGroupID          uint       `protobuf:"varint,10,opt,name=UserGroupID,proto3" json:"UserGroupID,omitempty"`
	Photo                string     `protobuf:"bytes,11,opt,name=Photo,proto3" json:"Photo,omitempty"`
	LastLogin            *time.Time `protobuf:"bytes,12,opt,name=LastLogin,proto3" json:"LastLogin,omitempty"`
	ExpiresOn            *time.Time `protobuf:"bytes,13,opt,name=ExpiresOn,proto3" json:"ExpiresOn,omitempty"`
	GeneratedOTPToVerify string     `protobuf:"bytes,14,opt,name=GeneratedOTPToVerify,proto3" json:"GeneratedOTPToVerify,omitempty"`
	OTPSeed              string     `protobuf:"bytes,15,opt,name=OTPSeed,proto3" json:"OTPSeed,omitempty"`
	Salt                 string     `protobuf:"bytes,16,opt,name=Salt,proto3" json:"Salt,omitempty"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba69147a0c9d872, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_User.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return m.Size()
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *User) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *User) GetRemoteAccess() bool {
	if m != nil {
		return m.RemoteAccess
	}
	return false
}

func (m *User) GetUserGroup() *UserGroup {
	if m != nil {
		return &m.UserGroup
	}
	return nil
}

func (m *User) GetUserGroupID() uint {
	if m != nil {
		return m.UserGroupID
	}
	return 0
}

func (m *User) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *User) GetLastLogin() *time.Time {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *User) GetExpiresOn() *time.Time {
	if m != nil {
		return m.ExpiresOn
	}
	return nil
}

func (m *User) GetGeneratedOTPToVerify() string {
	if m != nil {
		return m.GeneratedOTPToVerify
	}
	return ""
}

func (m *User) GetOTPSeed() string {
	if m != nil {
		return m.OTPSeed
	}
	return ""
}

func (m *User) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "models.User")
}

func init() {
	proto.RegisterFile("blueprint/user/models/generatemodels.proto", fileDescriptor_5ba69147a0c9d872)
}

var fileDescriptor_5ba69147a0c9d872 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x6e, 0xe2, 0x30,
	0x14, 0x86, 0xc9, 0x00, 0x01, 0x0c, 0x73, 0x91, 0x85, 0x46, 0xd6, 0x68, 0x14, 0x45, 0xac, 0xd0,
	0x2c, 0x88, 0x34, 0xf3, 0x04, 0x8c, 0x4a, 0x69, 0x25, 0x54, 0xa2, 0x40, 0xbb, 0xe8, 0x2e, 0x24,
	0xa7, 0x60, 0x29, 0x89, 0x23, 0xdb, 0xe9, 0xe5, 0x2d, 0xfa, 0x58, 0x5d, 0xb2, 0xe8, 0xa2, 0xcb,
	0x0a, 0x5e, 0xa4, 0xb2, 0x4d, 0xd2, 0x56, 0x62, 0xe5, 0x7c, 0xff, 0x77, 0xec, 0x1c, 0x27, 0x07,
	0xfd, 0x59, 0x25, 0x05, 0xe4, 0x9c, 0x66, 0xd2, 0x2b, 0x04, 0x70, 0x2f, 0x65, 0x31, 0x24, 0xc2,
	0x5b, 0x43, 0x06, 0x3c, 0x94, 0x60, 0x70, 0x94, 0x73, 0x26, 0x19, 0xb6, 0x0d, 0x0d, 0x9e, 0xeb,
	0xa8, 0x71, 0x29, 0x80, 0xe3, 0x5f, 0xa8, 0xad, 0xd6, 0x2c, 0x4c, 0x81, 0x58, 0xae, 0x35, 0xec,
	0x04, 0x15, 0xe3, 0xdf, 0xa8, 0x73, 0x4a, 0xb9, 0x90, 0x17, 0x4a, 0x7e, 0xd1, 0xf2, 0x3d, 0x50,
	0x3b, 0x67, 0xe1, 0x41, 0xd6, 0xcd, 0xce, 0x92, 0x95, 0xf3, 0x43, 0x21, 0xee, 0x18, 0x8f, 0x49,
	0xc3, 0xb8, 0x92, 0x71, 0x1f, 0x35, 0x27, 0x69, 0x48, 0x13, 0xd2, 0xd4, 0xc2, 0x00, 0xfe, 0x89,
	0xec, 0x71, 0x24, 0xe9, 0x2d, 0x10, 0xdb, 0xb5, 0x86, 0xed, 0xe0, 0x40, 0xaa, 0x7a, 0x1c, 0xa7,
	0x34, 0x23, 0x2d, 0x1d, 0x1b, 0xc0, 0x03, 0xd4, 0x0b, 0x20, 0x65, 0x12, 0xc6, 0x51, 0x04, 0x42,
	0x90, 0xb6, 0x96, 0x9f, 0x32, 0xd5, 0xbd, 0xba, 0xc9, 0x94, 0xb3, 0x22, 0x27, 0x1d, 0xd3, 0x7d,
	0x15, 0x60, 0x17, 0x75, 0x2b, 0x38, 0x3f, 0x21, 0xc8, 0xb5, 0x86, 0xcd, 0xe0, 0x63, 0xa4, 0xde,
	0xec, 0x6f, 0x98, 0x64, 0xa4, 0x6b, 0xfa, 0xd4, 0xa0, 0x4e, 0x55, 0xb7, 0x9c, 0xb1, 0x35, 0xcd,
	0x48, 0xcf, 0x9c, 0x5a, 0x05, 0xca, 0x4e, 0xee, 0x73, 0xca, 0x41, 0xcc, 0x33, 0xf2, 0xd5, 0xd8,
	0x2a, 0xc0, 0x7f, 0x51, 0x7f, 0x7a, 0xf8, 0x29, 0xf1, 0x7c, 0xe9, 0x2f, 0xd9, 0x15, 0x70, 0x7a,
	0xf3, 0x40, 0xbe, 0xe9, 0xc2, 0xa3, 0x0e, 0x13, 0xd4, 0x9a, 0x2f, 0xfd, 0x05, 0x40, 0x4c, 0xbe,
	0xeb, 0xb2, 0x12, 0x31, 0x46, 0x8d, 0x45, 0x98, 0x48, 0xf2, 0x43, 0xc7, 0xfa, 0xf9, 0xff, 0xd9,
	0xd3, 0xce, 0xb1, 0xb6, 0x3b, 0xc7, 0x7a, 0xdd, 0x39, 0xd6, 0xe3, 0xde, 0xa9, 0x6d, 0xf7, 0x4e,
	0xed, 0x65, 0xef, 0xd4, 0xae, 0x47, 0x6b, 0x2a, 0x37, 0xc5, 0x6a, 0x14, 0xb1, 0xd4, 0x2b, 0x42,
	0xf5, 0x11, 0xcb, 0xe5, 0xe8, 0xf4, 0xac, 0x6c, 0x3d, 0x2f, 0xff, 0xde, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xc6, 0x32, 0x62, 0x43, 0x5d, 0x02, 0x00, 0x00,
}

func (m *User) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *User) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *User) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.OTPSeed) > 0 {
		i -= len(m.OTPSeed)
		copy(dAtA[i:], m.OTPSeed)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.OTPSeed)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.GeneratedOTPToVerify) > 0 {
		i -= len(m.GeneratedOTPToVerify)
		copy(dAtA[i:], m.GeneratedOTPToVerify)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.GeneratedOTPToVerify)))
		i--
		dAtA[i] = 0x72
	}
	//if len(m.ExpiresOn) > 0 {
	//	i -= len(m.ExpiresOn)
	//	copy(dAtA[i:], m.ExpiresOn)
	//	i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.ExpiresOn)))
	//	i--
	//	dAtA[i] = 0x6a
	//}
	//if len(m.LastLogin) > 0 {
	//	i -= len(m.LastLogin)
	//	copy(dAtA[i:], m.LastLogin)
	//	i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.LastLogin)))
	//	i--
	//	dAtA[i] = 0x62
	//}
	if len(m.Photo) > 0 {
		i -= len(m.Photo)
		copy(dAtA[i:], m.Photo)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.Photo)))
		i--
		dAtA[i] = 0x5a
	}
	if m.UserGroupID != 0 {
		i = encodeVarintGeneratemodels(dAtA, i, uint64(m.UserGroupID))
		i--
		dAtA[i] = 0x50
	}
	//if len(m.UserGroup) > 0 {
	//	i -= len(m.UserGroup)
	//	copy(dAtA[i:], m.UserGroup)
	//	i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.UserGroup)))
	//	i--
	//	dAtA[i] = 0x4a
	//}
	if m.RemoteAccess {
		i--
		if m.RemoteAccess {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.Admin {
		i--
		if m.Admin {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LastName) > 0 {
		i -= len(m.LastName)
		copy(dAtA[i:], m.LastName)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.LastName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FirstName) > 0 {
		i -= len(m.FirstName)
		copy(dAtA[i:], m.FirstName)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.FirstName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintGeneratemodels(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGeneratemodels(dAtA []byte, offset int, v uint64) int {
	offset -= sovGeneratemodels(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *User) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	l = len(m.FirstName)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	l = len(m.LastName)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	if m.Active {
		n += 2
	}
	if m.Admin {
		n += 2
	}
	if m.RemoteAccess {
		n += 2
	}
	//l = len(m.UserGroup)
	//if l > 0 {
	//	n += 1 + l + sovGeneratemodels(uint64(l))
	//}
	if m.UserGroupID != 0 {
		n += 1 + sovGeneratemodels(uint64(m.UserGroupID))
	}
	l = len(m.Photo)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	//l = len(m.LastLogin)
	//if l > 0 {
	//	n += 1 + l + sovGeneratemodels(uint64(l))
	//}
	//l = len(m.ExpiresOn)
	//if l > 0 {
	//	n += 1 + l + sovGeneratemodels(uint64(l))
	//}
	l = len(m.GeneratedOTPToVerify)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	l = len(m.OTPSeed)
	if l > 0 {
		n += 1 + l + sovGeneratemodels(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 2 + l + sovGeneratemodels(uint64(l))
	}
	return n
}

func sovGeneratemodels(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGeneratemodels(x uint64) (n int) {
	return sovGeneratemodels(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *User) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGeneratemodels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: User: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: User: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Admin = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteAccess", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RemoteAccess = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserGroup", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			// m.UserGroup = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserGroupID", wireType)
			}
			m.UserGroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				// m.UserGroupID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Photo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Photo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastLogin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			// m.LastLogin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresOn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			// m.ExpiresOn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GeneratedOTPToVerify", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GeneratedOTPToVerify = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OTPSeed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OTPSeed = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGeneratemodels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGeneratemodels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGeneratemodels(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGeneratemodels
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGeneratemodels
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGeneratemodels
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGeneratemodels
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGeneratemodels
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGeneratemodels        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGeneratemodels          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGeneratemodels = fmt.Errorf("proto: unexpected end of group")
)
